Feature/appeal number 399
Cour-de-cassation/label pull request #82
Opened 2024-02-15 15:01 UTC by Bouba-cassation

## Issue description :

## Describe your changes :

## How to test :

## Checklist before requesting a review
- [ ] I have performed a self-review of my code.
- [ ] The feature works locally.
- [ ] If it's relevant I added tests.
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

2024-03-11 16:50 UTC, ajeanneney requested changes
Dans l'ensemble il faut nettoyer un peu le code de ses commentaires/logs, clarifier le nom/l'usage des différentes fonctions et factoriser la logique qui peut être factorisée pour améliorer la lisibilité et la maintenance du code

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +function isCorrectAppeal(value: string | undefined) {
Si le nom de la fonction est `isCorrect...` il vaut mieux qu'elle return un boolean

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +function isCorrectAppeal(value: string | undefined) {
Et qu'elle ne puisse pas accepter `undefined` en entrée

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  const appeals = sderCourtDecision.appeals[0];
si il n'y a qu'une valeur a `appeals` on peut la mettre au singulier

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  const numeroRoleGeneral = sderCourtDecision.numeroRoleGeneral || '';
Pourquoi un `|| ''` sur le `numeroRoleGeneral` et pas sur le `register` ou le `appeal` ?

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +  source?: string,
On peut rendre la source obligatoire, je ne vois pas de cas ou un décision arrive sans source

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +  if (source != '' || undefined) {
Comme il y a des return a chaque possibilité (donc on quitte la fonction) ce if n'a pas d'utilité, tu peux laisser juste un `return regexExtractAppealNumber(text);` avant la fin de la fonction cela aura le meme effet
Dans l'ensemble de la fonction on peut s'arranger pour n'avoir qu'un seul appel a la fonction `regexExtractAppealNumber`

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +function titleAppealNumber(
Peut-être a renomer en `getNumberPrefix` ou `getAppealNumberPrefix`

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  if (source === 'jurica' || source === 'juritj') {
on peut factoriser avec un truc dans le genre :
 ```
if (readableJurisdictionName?.includes('cassation')) {
    return (appealNumber = `Pourvoi n° ${appealNumber}`);
} else {
    return (appealNumber = `RG n° ${appealNumber}`);
}
```

2024-03-11 16:50 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  2;
to delete ;)

2024-03-13 12:05 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  2;
good

2024-03-13 13:15 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  if (source === 'jurica' || source === 'juritj') {
if (readableJurisdictionName?.includes('cassation') && source !== 'jurica' || source !== 'juritj') {
    return (appealNumber = `Pourvoi n° ${appealNumber}`);
  } else {
    return (appealNumber = `RG n° ${appealNumber}`);
  }

2024-03-13 13:17 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +function titleAppealNumber(
getNumberPrefix

2024-03-13 14:02 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  const numeroRoleGeneral = sderCourtDecision.numeroRoleGeneral || '';
Obliger car il arrive que l'on ai des décisions sans numeroRoleGenerale  donc undefined, et en plus dans sder-api-types, numeroRoleGenerale est en optional, ce qui n'est pas le cas de appeals et resgisterNumber.

2024-03-13 14:03 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +function isCorrectAppeal(value: string | undefined) {
j'ai changer le nom de la fonction, obliger de retourner ma valeur

2024-03-13 14:49 UTC, Bouba-cassation commented
Nous devons récupérer la bonne version de commit de sder (pour avoir numeroRoleGeneral)

2024-03-20 16:21 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  source === 'juritj'
remplacer par un if

2024-03-20 16:21 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +    'juritj'
'juritj' est toujouts true

2024-03-20 16:21 UTC, ajeanneney commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +  if (source === 'jurica' && registerNumber != '') {
Si on met : 
```
if (source === 'jurica' || registerNumber != '' || registerNumber != undefined) {
    return registerNumber?.split(' ')[0]
```
et qu'on fait de manière similaire pour les autres if ça nous permet d'avoir un else général qui va utiliser la regex ==> code plus compacte / lisible

2024-03-22 10:40 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +  source === 'juritj'
good

2024-03-22 10:45 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/mapCourtDecisionToDocument.ts
> +    'juritj'
adding  (readableJurisdictionName?.includes('cassation') && source !== 'jurica') ||
    source !== 'juritj'

2024-03-22 10:45 UTC, Bouba-cassation commented on packages/courDeCassation/src/connector/mapper/extractors/extractAppealRegisterRoleGeneralNumber.ts
> +  if (source === 'jurica' && registerNumber != '') {
Good

2024-03-25 08:38 UTC, ajeanneney approved these changes

2024-03-25 13:16 UTC, merged